export const BASE_URL = 'https://shotnotes.dev.doozycodsystems.com/API/';

const api = {
  SIGNIN: BASE_URL + 'user/register.php',
  LOGIN: BASE_URL + 'user/login.php',
  FORGET: BASE_URL + 'user/recover-password.php',
  LOGOUT: BASE_URL + 'user/logout.php',
  CHANGEPASSWORD: BASE_URL + 'user/update-password.php',
  SOCIAL_LOGIN: BASE_URL + 'user/register1.php',
  CREATE_COURSE: BASE_URL + '/courses/create-course.php',
  ALL_COURSE: BASE_URL + 'courses/get-all-courses.php',
  MY_COURSE: BASE_URL + 'courses/get-user-courses.php',
  GET_CHAPTER: BASE_URL + 'courses/get-course-chapter.php',
  ADD_CHAPTER: BASE_URL + 'courses/create-chapter.php',
  SAVE_PAYMENT: BASE_URL + 'courses/savepayment.php',
  PURCHASED_COURSE: BASE_URL + 'courses/get-user-purchased-courses.php',
  CREATE_CARD: BASE_URL + 'courses/create-card.php',
  GET_ALL_CARD: BASE_URL + 'courses/get-all-cards.php',
  GET_CARD: BASE_URL + 'courses/get-card-details.php',
  GET_REMANING: BASE_URL + 'courses/get-remaining-cards.php',
  MOVE_CARDS: BASE_URL + 'courses/move-cards-to-deck.php',
  COUNT_DECK: BASE_URL + 'courses/get-count-all-decks.php',
  GET_REVISION: BASE_URL + 'courses/get-revision-cards.php',
  UPDATE_REVISION: BASE_URL + 'courses/update-card-status.php',
  SAVE_BOOKMARK: BASE_URL + 'courses/user-bookmark-cards.php',
  EDIT_COURSE: BASE_URL + 'courses/update-course.php',
  UPDATE_CHAPTER: BASE_URL + 'courses/update-chapter.php',
  RESET_REVISION: BASE_URL + 'courses/reset-revision.php',
  GET_USERDATA: BASE_URL + 'user/get-user-data.php',
  USER_FEEDBACK: BASE_URL + 'courses/user-feedback.php',
  COURSE_FEEDBACK: BASE_URL + 'courses/course-feedback.php',
  GET_WALLET: BASE_URL + 'courses/get-wallet.php',
  REQUEST_WALLET: BASE_URL + 'courses/request-payment.php',
  GET_CARD_DATA: BASE_URL + 'courses/get-card-details.php',
  UPDATE_CARD: BASE_URL + 'courses/update-card.php',
  UPDATE_USER: BASE_URL + 'user/update-user-details.php',
  UPDATE_IMAGE: BASE_URL + 'user/update-profile-picture.php',
  EXPLORE: BASE_URL + 'courses/get-explore-courses.php',
  ACCOUNT_SAVE: BASE_URL + 'user/save-bank-account.php',
  ACCOUNT_UPDATE: BASE_URL + 'user/update-bank-account.php',
  ACCOUNT_INFO: BASE_URL + 'user/get-user-bank-account-details.php',
  DELETE_CARD: BASE_URL + 'courses/delete-data.php',
  REMOVE_COURSE: BASE_URL + 'courses/remove-course-from-downloads.php',
};
export default api;
